### ISSUE TITLE
ios: show access-lists error with ACL containing icmp ttl-exceeded

### ISSUE THREAD

**Issue by ciscopony** [CiscoTestAutomation/genieparser#71] opened 2020-01-07 22:21 UTC
Attempting to parse an access-list that reads as follows in "show access-lists":

>Extended IP access list Public_Trust
>    10 permit icmp any any echo
>    20 permit icmp any any echo-reply (1195 matches)
>    30 permit icmp any any ttl-exceeded
>    40 permit icmp any any unreachable
>    50 permit icmp any any packet-too-big
>    60 deny icmp any any
>    70 permit ip object-group grt-interface-nets object-group grt-interface-nets
>    80 permit udp any host 224.0.0.102 eq 1985

Generates the following error:

> $ genie parse "show access-lists" --testbed-file gns3.yml --devices rtr-ipsec-vlab1-a 
  0%|                                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]Issue with the parser show access-lists
Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 289, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/josiemer/configs/Automation/pyATS/venv/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_acl.py", line 478, in cli
    l3_dict['ttl_operator'] = ttl_group.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

I initially thought this error was related to the access-list containing object-groups, but the actual cause seems to be this line:

> permit icmp any any ttl-exceeded

Looking at the code it appears the parser is attempting to make some kind of sense of whatever text might follow "ttl" in this part of an ACL and failing. Removing this line of the ACL will allow it to be processed.

**Comment by thaixuann** [comment] 2020-01-08 00:14
Hello @ciscopony ,
Thanks for reporting. We'll take a look and let you know once the issue is fixed.

Thanks,
--Thai.

**Comment by thaixuann** [comment] 2020-02-06 00:26
Hello @ciscopony ,
We fixed the issue and genie package v20.1 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install genie.libs.parser --upgrade --pre

Thanks,
--Thai.

**Closed** 2020-02-19 16:51 UTC
Labels: bug
