### ISSUE TITLE
[IOS-XE] Parser for "show interfaces" does not work when CVR-QSFP-SFP10G is inserted in interface

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#868] opened 2024-07-13 15:20 UTC
Sample CLI output, where a CVR-QSFP-SFP10G transceiver is inserted in an interface, and a SFP-10G-SR is inserted within that:
```
HundredGigE1/0/9 is up, line protocol is up (connected) 
  Hardware is Hundred Gigabit Ethernet, address is 6c03.b5fd.c629 (bia 6c03.b5fd.c629)
  Description: TTP1
  MTU 9216 bytes, BW 10000000 Kbit/sec, DLY 10 usec, 
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full-duplex, 10Gb/s, link type is auto, media type is CVR QSFP SFP10G(SFP-10GBase-SR)
  input flow-control is on, output flow-control is off
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input 00:00:07, output 00:00:00, output hang never
  Last clearing of "show interface" counters 5d21h
  Input queue: 0/2000/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     12331 packets input, 4631618 bytes, 0 no buffer
     Received 12331 broadcasts (12330 multicasts)
     0 runts, 0 giants, 0 throttles 
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 12330 multicast, 0 pause input
     0 input packets with dribble condition detected
     567643 packets output, 41033988 bytes, 0 underruns
     Output 0 broadcasts (516883 multicasts)
     0 output errors, 0 collisions, 2 interface resets
     0 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
```
The corresponding Genie parser output is missing speed, duplex, link type, and media type information:
```json
{
    "HundredGigE1/0/9": {
        "arp_timeout": "04:00:00",
        "arp_type": "arpa",
        "bandwidth": 10000000,
        "connected": True,
        "counters": {
            "in_broadcast_pkts": 12331,
            "in_crc_errors": 0,
            "in_errors": 0,
            "in_frame": 0,
            "in_giants": 0,
            "in_ignored": 0,
            "in_mac_pause_frames": 0,
            "in_multicast_pkts": 12330,
            "in_no_buffer": 0,
            "in_octets": 4631618,
            "in_overrun": 0,
            "in_pkts": 12331,
            "in_runts": 0,
            "in_throttles": 0,
            "in_watchdog": 0,
            "in_with_dribble": 0,
            "last_clear": "5d21h",
            "out_babble": 0,
            "out_broadcast_pkts": 0,
            "out_buffer_failure": 0,
            "out_buffers_swapped": 0,
            "out_collision": 0,
            "out_deferred": 0,
            "out_errors": 0,
            "out_interface_resets": 2,
            "out_late_collision": 0,
            "out_lost_carrier": 0,
            "out_mac_pause_frames": 0,
            "out_multicast_pkts": 516883,
            "out_no_carrier": 0,
            "out_octets": 41033988,
            "out_pkts": 567643,
            "out_underruns": 0,
            "out_unknown_protocl_drops": 0,
            "rate": {
                "in_rate": 0,
                "in_rate_pkts": 0,
                "load_interval": 300,
                "out_rate": 0,
                "out_rate_pkts": 0,
            },
        },
        "delay": 10,
        "description": "TTP1",
        "enabled": True,
        "encapsulations": {
            "encapsulation": "arpa",
        },
        "err_disabled": False,
        "flow_control": {
            "receive": True,
            "send": False,
        },
        "is_deleted": False,
        "keepalive": 10,
        "last_input": "00:00:07",
        "last_output": "00:00:00",
        "line_protocol": "up",
        "mac_address": "6c03.b5fd.c629",
        "mtu": 9216,
        "oper_status": "up",
        "output_hang": "never",
        "phys_address": "6c03.b5fd.c629",
        "port_channel": {
            "port_channel_member": False,
        },
        "queues": {
            "input_queue_drops": 0,
            "input_queue_flushes": 0,
            "input_queue_max": 2000,
            "input_queue_size": 0,
            "output_queue_max": 40,
            "output_queue_size": 0,
            "queue_strategy": "fifo",
            "total_output_drop": 0,
        },
        "reliability": "255/255",
        "rxload": "1/255",
        "suspended": False,
        "txload": "1/255",
        "type": "Hundred Gigabit Ethernet",
    },
}
```
I would expect the output to look something like this:
```json
expected_output = {
    "HundredGigE1/0/9": {
        "arp_timeout": "04:00:00",
        "arp_type": "arpa",
        "bandwidth": 10000000,
        "connected": True,
        "counters": {
            "in_broadcast_pkts": 12331,
            "in_crc_errors": 0,
            "in_errors": 0,
            "in_frame": 0,
            "in_giants": 0,
            "in_ignored": 0,
            "in_mac_pause_frames": 0,
            "in_multicast_pkts": 12330,
            "in_no_buffer": 0,
            "in_octets": 4631618,
            "in_overrun": 0,
            "in_pkts": 12331,
            "in_runts": 0,
            "in_throttles": 0,
            "in_watchdog": 0,
            "in_with_dribble": 0,
            "last_clear": "5d21h",
            "out_babble": 0,
            "out_broadcast_pkts": 0,
            "out_buffer_failure": 0,
            "out_buffers_swapped": 0,
            "out_collision": 0,
            "out_deferred": 0,
            "out_errors": 0,
            "out_interface_resets": 2,
            "out_late_collision": 0,
            "out_lost_carrier": 0,
            "out_mac_pause_frames": 0,
            "out_multicast_pkts": 516883,
            "out_no_carrier": 0,
            "out_octets": 41033988,
            "out_pkts": 567643,
            "out_underruns": 0,
            "out_unknown_protocl_drops": 0,
            "rate": {
                "in_rate": 0,
                "in_rate_pkts": 0,
                "load_interval": 300,
                "out_rate": 0,
                "out_rate_pkts": 0,
            },
        },
        "delay": 10,
        "description": "TTP1",
        "enabled": True,
        "encapsulations": {
            "encapsulation": "arpa",
        },
        "duplex_mode": "full",
        "port_speed": "10Gb/s",
        "link_type": "auto",
        "auto_negotiate": False,
        "media_type": "CVR QSFP SFP10G(SFP-10GBase-SR)",
        "err_disabled": False,
        "flow_control": {
            "receive": True,
            "send": False,
        },
        "is_deleted": False,
        "keepalive": 10,
        "last_input": "00:00:07",
        "last_output": "00:00:00",
        "line_protocol": "up",
        "mac_address": "6c03.b5fd.c629",
        "mtu": 9216,
        "oper_status": "up",
        "output_hang": "never",
        "phys_address": "6c03.b5fd.c629",
        "port_channel": {
            "port_channel_member": False,
        },
        "queues": {
            "input_queue_drops": 0,
            "input_queue_flushes": 0,
            "input_queue_max": 2000,
            "input_queue_size": 0,
            "output_queue_max": 40,
            "output_queue_size": 0,
            "queue_strategy": "fifo",
            "total_output_drop": 0,
        },
        "reliability": "255/255",
        "rxload": "1/255",
        "suspended": False,
        "txload": "1/255",
        "type": "Hundred Gigabit Ethernet",
    },
}
```

**Comment by Harishv01** [comment] 2024-07-16 13:24
Hi, Okay, kindly give me some time to reproduce and fix the issue. Thank you.

**Comment by Harishv01** [comment] 2024-07-17 11:59
Hi,

I have fixed it and the output looks like below. Kindly check the output and let me know if everything is correct or not. If accurate, I will raise a PR.

```
expected_output ={
    "HundredGigE1/0/9": {
        "port_channel": {
            "port_channel_member": False
        },
        "is_deleted": False,
        "enabled": True,
        "line_protocol": "up",
        "oper_status": "up",
        "connected": True,
        "err_disabled": False,
        "suspended": False,
        "type": "Hundred Gigabit Ethernet",
        "mac_address": "6c03.b5fd.c629",
        "phys_address": "6c03.b5fd.c629",
        "description": "TTP1",
        "delay": 10,
        "mtu": 9216,
        "bandwidth": 10000000,
        "reliability": "255/255",
        "txload": "1/255",
        "rxload": "1/255",
        "encapsulations": {
            "encapsulation": "arpa"
        },
        "keepalive": 10,
        "duplex_mode": "full",
        "port_speed": "10gb/s",
        "link_type": "auto",
        "auto_negotiate": True,
        "media_type": "CVR QSFP SFP10G(SFP-10GBase-SR)",
        "flow_control": {
            "receive": True,
            "send": False
        },
        "arp_type": "arpa",
        "arp_timeout": "04:00:00",
        "last_input": "00:00:07",
        "last_output": "00:00:00",
        "output_hang": "never",
        "queues": {
            "input_queue_size": 0,
            "input_queue_max": 2000,
            "input_queue_drops": 0,
            "input_queue_flushes": 0,
            "total_output_drop": 0,
            "queue_strategy": "fifo",
            "output_queue_size": 0,
            "output_queue_max": 40
        },
        "counters": {
            "rate": {
                "load_interval": 300,
                "in_rate": 0,
                "in_rate_pkts": 0,
                "out_rate": 0,
                "out_rate_pkts": 0
            },
            "last_clear": "5d21h",
            "in_pkts": 12331,
            "in_octets": 4631618,
            "in_no_buffer": 0,
            "in_multicast_pkts": 12330,
            "in_broadcast_pkts": 12331,
            "in_runts": 0,
            "in_giants": 0,
            "in_throttles": 0,
            "in_errors": 0,
            "in_crc_errors": 0,
            "in_frame": 0,
            "in_overrun": 0,
            "in_ignored": 0,
            "in_watchdog": 0,
            "in_mac_pause_frames": 0,
            "in_with_dribble": 0,
            "out_pkts": 567643,
            "out_octets": 41033988,
            "out_underruns": 0,
            "out_broadcast_pkts": 0,
            "out_multicast_pkts": 516883,
            "out_errors": 0,
            "out_interface_resets": 2,
            "out_collision": 0,
            "out_unknown_protocl_drops": 0,
            "out_babble": 0,
            "out_late_collision": 0,
            "out_deferred": 0,
            "out_lost_carrier": 0,
            "out_no_carrier": 0,
            "out_mac_pause_frames": 0,
            "out_buffer_failure": 0,
            "out_buffers_swapped": 0
        }
    }
}
```

**Comment by ChristopherJHart** [comment] 2024-07-20 13:20
Hi @Harishv01 - that looks accurate to me. Thank you!

**Comment by Harishv01** [comment] 2024-07-24 16:19
We have merged the PR and the fix will be available in the next version, i.e., 24.7. Hence, I am closing the ticket. Thank you.

**Closed by Harishv01** 2024-07-24 16:19 UTC
