### ISSUE TITLE
IOS-XE Show ip nat translation, cannot find parser

### ISSUE THREAD

**Issue by ogruca** [CiscoTestAutomation/genieparser#98] opened 2020-03-09 07:56 UTC
Hello
I am running the geneie command below and its failing to find a parser.
 genie parse "show ip nat translations verbose" --testbed-file prod-pyats-testbed.yaml --device NSY1AGG008 -v

Here are the python details, pythong 3.7 virtual env
Cisco ASR 1002 asr1000rp2-adventerprisek9.03.16.09.S.155-3.S9-ext.bi

Package                      Version    
---------------------------- -----------
arrow                        0.15.5     
asn1crypto                   0.24.0     
backports.ssl                0.0.9      
binaryornot                  0.4.4      
certifi                      2019.6.16  
cffi                         1.12.3     
chardet                      3.0.4      
Click                        7.0        
cookiecutter                 1.7.0      
cryptography                 2.7        
dill                         0.3.0      
distro                       1.4.0      
future                       0.18.2     
genie                        19.7.1     
genie.abstract               19.7       
genie.conf                   19.7.2     
genie.harness                19.7.2     
genie.libs.conf              19.7       
genie.libs.filetransferutils 19.7       
genie.libs.ops               19.7       
genie.libs.parser            19.7       
genie.libs.robot             20.1       
genie.libs.sdk               19.7       
genie.libs.telemetry         19.7       
genie.metaparser             19.7       
genie.ops                    19.7       
genie.parsergen              19.7       
genie.predcore               19.7       
genie.telemetry              19.7       
genie.trafficgen             19.7.1     
genie.utils                  19.7       
idna                         2.8        
IxNetwork                    9.0.1915.16
Jinja2                       2.10.1     
jinja2-time                  0.2.0      
jsonpickle                   1.2        
junit-xml                    1.8        
MarkupSafe                   1.1.1      
netaddr                      0.7.19     
pathspec                     0.5.9      
pip                          20.0.2     
poyo                         0.5.0      
prettytable                  0.7.2      
psutil                       5.6.3      
pyats                        19.7       
pyats.aereport               19.7       
pyats.aetest                 19.7       
pyats.async                  19.7       
pyats.connections            19.7       
pyats.datastructures         19.7       
pyats.easypy                 19.7       
pyats.kleenex                19.7       
pyats.log                    19.7       
pyats.results                19.7       
pyats.robot                  19.7       
pyats.tcl                    19.7       
pyats.topology               19.7       
pyats.utils                  19.7       
pycparser                    2.19       
pyOpenSSL                    19.0.0     
python-dateutil              2.8.1      
PyYAML                       5.1.2      
requests                     2.22.0     
robotframework               3.1.2      
setproctitle                 1.1.10     
setuptools                   40.8.0     
six                          1.12.0     
tqdm                         4.35.0     
unicon                       19.7.5     
urllib3                      1.25.3     
websocket-client             0.56.0     
wheel                        0.33.6     
whichcraft                   0.6.1      
xmltodict                    0.12.0     
yamllint                     1.17.0 

output
NSY1AGG008#
[2020-03-09 18:47:12,912] +++ initializing handle +++
[2020-03-09 18:47:12,912] +++ NSY1AGG008: executing command 'term length 0' +++
term length 0
NSY1AGG008#
[2020-03-09 18:47:12,943] +++ NSY1AGG008: executing command 'term width 0' +++
term width 0
NSY1AGG008#
[2020-03-09 18:47:12,971] +++ NSY1AGG008: executing command 'show version' +++
show version
Cisco IOS XE Software, Version 03.16.09.S - Extended Support Release
Cisco IOS Software, ASR1000 Software (X86_64_LINUX_IOSD-ADVENTERPRISEK9-M), Version 15.5(3)S9, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Mon 18-Mar-19 06:25 by mcpre

Cisco IOS-XE software, Copyright (c) 2005-2019 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.

ROM: IOS-XE ROMMON

NSY1AGG008 uptime is 20 weeks, 5 days, 19 hours, 27 minutes
Uptime for this control processor is 20 weeks, 5 days, 19 hours, 29 minutes
System returned to ROM by reload at 23:20:12 AEDST Tue Oct 15 2019
System restarted at 23:20:37 AEDST Tue Oct 15 2019
System image file is "bootflash:asr1000rp2-adventerprisek9.03.16.09.S.155-3.S9-ext.bi"
Last reload reason: Reload Command

This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

cisco ASR1004 (RP2) processor (revision RP2) with 1479776K/6147K bytes of memory.
Processor board ID FXS1946Q2R6
5 Gigabit Ethernet interfaces
3 Ten Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
8388608K bytes of physical memory.
1873919K bytes of eUSB flash at bootflash:.
78085207K bytes of SATA hard disk at harddisk:.
15856K bytes of obfl at obfl:.

Configuration register is 0x2102

NSY1AGG008#
  0%|                                                                                                                     | 0/1 [00:00<?, ?it/s]Could not find parser for 'show ip nat translations
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.44it/s]

**Comment by xiaoxinz-cisco** [comment] 2020-03-09 13:38
Hello @ogruca ,

The latest version of pyATS and Genie is [v20.2](https://developer.cisco.com/docs/genie-docs/).
Try update using `pip install --upgrade pyats[full]` and see if it works.

Thanks,
Irene

**Comment by ogruca** [comment] 2020-03-09 13:54
thank you i will try

**Comment by ogruca** [comment] 2020-03-10 12:08
Upgraded to 20.2, still showing error when trying to parse show ip nat translations.....other parsers  work.
(pyats-genie) ogruca@ubuntu:~/scripts/pyats$ genie parse "show ip nat translations" --testbed-file prod-pyats-testbed.yaml --devices NSY1AGG008 --output output/NSY1AGG008
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.09it/s]
+==============================================================================+
| Genie Parse Summary for NSY1AGG008                                           |
+==============================================================================+
|  Connected to NSY1AGG008                                                     |
|  -  Log: output/NSY1AGG008/connection_NSY1AGG008.txt                         |
|------------------------------------------------------------------------------|
| Could not find parser for 'show ip nat translations'                         |
|------------------------------------------------------------------------------|

(pyats-genie) ogruca@ubuntu:~/scripts/pyats$ genie parse "show ip interface" --testbed-file prod-pyats-testbed.yaml --devices NSY1AGG008 --output output/NSY1AGG008
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.41s/it]
+==============================================================================+
| Genie Parse Summary for NSY1AGG008                                           |
+==============================================================================+
|  Connected to NSY1AGG008                                                     |
|  -  Log: output/NSY1AGG008/connection_NSY1AGG008.txt                         |
|------------------------------------------------------------------------------|
|  Parsed command 'show ip interface'                                          |
|  -  Parsed structure: output/NSY1AGG008/NSY1AGG008_show-ip-                  |
| interface_parsed.txt                                                         |
|  -  Device Console:   output/NSY1AGG008/NSY1AGG008_show-ip-                  |
| interface_console.txt                                                        |
|------------------------------------------------------------------------------|

(pyats-genie) ogruca@ubuntu:~/scripts/pyats$



output from pip list
(pyats-genie) ogruca@ubuntu:~/scripts/pyats$ pip list
Package                      Version   
---------------------------- ----------
aiohttp                      3.6.2     
async-timeout                3.0.1     
attrs                        19.3.0    
certifi                      2019.11.28
chardet                      3.0.4     
dill                         0.3.1.1   
distro                       1.4.0     
genie                        20.2      
genie.libs.conf              20.2      
genie.libs.filetransferutils 20.2      
genie.libs.ops               20.2      
genie.libs.parser            20.2      
genie.libs.sdk               20.2.2    
idna                         2.9       
Jinja2                       2.11.1    
jsonpickle                   1.3       
junit-xml                    1.9       
MarkupSafe                   1.1.1     
multidict                    4.7.5     
netaddr                      0.7.19    
pathspec                     0.7.0     
pip                          20.0.2    
prettytable                  0.7.2     
psutil                       5.7.0     
pyats                        20.2.1    
pyats.aereport               20.2      
pyats.aetest                 20.2      
pyats.async                  20.2      
pyats.connections            20.2      
pyats.datastructures         20.2      
pyats.easypy                 20.2      
pyats.kleenex                20.2      
pyats.log                    20.2      
pyats.reporter               20.2.2    
pyats.results                20.2      
pyats.tcl                    20.2      
pyats.topology               20.2      
pyats.utils                  20.2      
PyYAML                       5.3       
requests                     2.23.0    
setuptools                   40.8.0    
six                          1.14.0    
tqdm                         4.43.0    
unicon                       20.2      
unicon.plugins               20.2      
urllib3                      1.25.8    
xmltodict                    0.12.0    
yamllint                     1.20.0    
yarl                         1.4.2     
(pyats-genie) ogruca@ubuntu:~/scripts/pyats$

**Comment by xiaoxinz-cisco** [comment] 2020-03-10 15:45
Hello @ogruca ,

Thanks for pointing out. I found that the error is caused by a typo in the code.

In [the line72](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_ip_nat.py#L72), it should be `show ip nat translations`, hope it works!

I'll update and include it in the next release.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment] 2020-03-10 21:21
Hello @ogruca 

We fixed the issue and genie package **v20.2.1b0** has been released with the fix.
Could you please run the following command and try again to see if it works?

**pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene

**Closed** 2020-03-17 21:31 UTC
