### ISSUE TITLE
show policy-map interface output failing on queue stats for all priority classes

### ISSUE THREAD

**Issue by MikeJames15** [CiscoTestAutomation/genieparser#54] opened 2019-10-31 18:45 UTC
While trying to parse the output of the "show policy-map interface output" command the following error gets generated:

    File "src/genie/conf/base/device.py", line 498, in genie.conf.base.device.Device.parse
    File "src/genie/metaparser/_metaparser.py", line 271, in  genie.metaparser._metaparser.MetaParser.parse
    File "/home/mike/.local/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1271, in cli
    return super().cli(output=show_output)
    File "/home/mike/.local/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 941, in cli
      class_map_dict['queue_limit_packets'] = m.groupdict()['queue_limit']
    UnboundLocalError: local variable 'class_map_dict' referenced before assignment

The error is generated by the following data:

    TenGigabitEthernet0/1/0 
    
    Service-policy output: xxxx

    queue stats for all priority classes:
      Queueing
      queue limit 512 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0

    Class-map: yyyyyy (match-any)  

Looking at the source I found that the problem seems to be that the schema is expecting the stats for all classes to be under a class.
I verified this by replacing "queue stats for all priority classes:" with "Class-map: all_priority_classes (match-any)\nMatch: any" after which, the command output was parsed.
I had to add the Match: any for it to work. It would be nice for these stats to be parsed without mapping them to a class.

**Comment by thaixuann** [comment] 2019-10-31 19:35
Hi @MikeJames15 
Thanks for reporting the issue. We will look into it and let you know once the issue is fixed.

Thanks,
--Thai.

**Comment by thaixuann** [comment] 2019-11-06 18:42
Hello @MikeJames15 ,
Would you please provide the full output from the device for this command so that we can see if there is anything else we missed? Please send the output to pyats-support-ext@cisco.com.

Thanks,
--Thai.

**Comment by thaixuann** [comment] 2019-11-27 22:32
Hello @MikeJames15 ,
We fixed this issue. A pyats and genie package v19.11 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install --upgrade pyats
pip install --upgrade genie

Please let us know if you have question.

Thanks,
--Thai.

**Comment by jeaubin** [comment] 2019-12-06 23:52
Closing the issue @MikeJames15 

If the issue is still present, please let us know!

**Closed by jeaubin** 2019-12-06 23:52 UTC
Labels: bug
