### ISSUE TITLE
ios: show access-lists parse error for udp ACL with incremented counter

### ISSUE THREAD

**Issue by ciscopony** [CiscoTestAutomation/genieparser#72] opened 2020-01-07 22:50 UTC
Use case: there will be a pair of routers with the following ACL present for allowing HSRP broadcast traffic on interfaces:

> permit udp any host 224.0.0.102 eq 1985

Attempting to parse the access-lists of these devices will fail with the following traceback:
```
$ genie parse "show access-lists" --testbed-file gns3.yml --devices rtr-ipsec-vlab1-a 
  0%|                                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]Issue with the parser show access-lists


Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 302, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 277, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 302, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 277, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 245, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaTypeError: Public_Trust.aces.80.matches.l4.udp.destination_port.range.upper_port: Expected type '<class 'int'>' but got type '(80'(<class 'str'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 289, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 305, in genie.metaparser._metaparser.MetaParser.parse
Exception: Parser ShowAccessLists schema checking failed
''
```
The error seems to be due to the parser misinterpreting the number of matches for the rule in the "show access-lists" output:

```
Extended IP access list dummydpd-intacl
    10 permit icmp any any
    20 permit udp any host 224.0.0.102 eq 1985 (67 matches)
    30 permit ip object-group dummydpd-local object-group dummydpd-remote
```

IE, the parser seems to assume that the part in parenthesis on line 20 should be the second part of a port range or list of ports. This ACL will parse fine if there are no hits on the item in question, IE, if I turn off the interface on the other router in the HSRP pair so it's no longer generating this traffic and clear the access-list statistics it'll work. I'm able to replicate this with other sorts of udp traffic acls; for instance, having this in the show access-lists output:

>     30 permit udp any any eq isakmp (12 matches)

Generates the same traceback.

**Comment by thaixuann** [comment] 2020-01-08 00:18
Hello @ciscopony ,
Thanks for reporting. We will take a look and let you know once the issue is fixed.

Thanks,
--Thai.

**Comment by thaixuann** [comment] 2020-02-06 00:26
Hello @ciscopony ,

We fixed the issue and genie package v20.1 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install genie.libs.parser --upgrade --pre

Thanks,
--Thai.

**Closed** 2020-02-19 16:52 UTC
Labels: bug
