### ISSUE TITLE
Regex does not allow for sub-interfaces

### ISSUE THREAD

**Issue by rowco** [CiscoTestAutomation/genieparser#108] opened 2020-03-18 15:33 UTC
Hi,

Just hit a minor problem, where this regex doesn't allow for sub-interfaces.

I updated it to:
`\s*(?P<intf>[a-zA-Z0-9\/\.]+) +\- +Group`

https://github.com/CiscoTestAutomation/genieparser/blob/342fce12eb3fc6091944a4dff14fe5c6eb035795/src/genie/libs/parser/iosxe/show_standby.py#L402

Keep up the great work.

**Comment by xiaoxinz-cisco** [comment] 2020-03-18 15:48
Hi @rowco ,

Thanks for pointing out, could you please create a pull request? Our support team will review and merge it.

Thanks,
Irene

**Comment by urskog84** [comment] 2020-03-22 12:41
i have fix dis in my pull request https://github.com/CiscoTestAutomation/genieparser/pull/104
commit https://github.com/urskog84/genieparser/commit/0568e35afe78c3aac5bd47eb0c9be07b1212c9b5

**Comment by urskog84** [comment] 2020-03-22 14:54
duplicate of issue https://github.com/CiscoTestAutomation/genieparser/issues/103

**Closed** 2020-04-07 18:57 UTC
