### ISSUE TITLE
[IOS-XE] Parser for "show cdp neighbors" does not accommodate serial links

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#844] opened 2024-04-29 16:24 UTC
The parser for IOS-XE's `show cdp neighbors` command does not work if the local or remote interface contains a serial link.

Sample CLI output:
```
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone, 
                  D - Remote, C - CVTA, M - Two-port Mac Relay 

Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
R1.cisco.com
                 Gig 0/2/0         169              R I   ASR1002   Gig 0/0/0
R2.cisco.com
                 Gig 0/2/2         167             R B S  CISCO2951 Gig 0/0
R3.cisco.com
                 Multilink3        165              R I   ASR1002   Multilink1
R4.cisco.com
                 Ser 0/1/0:0       160             R S I  ISR4451-X Ser 0/1/0:0

Total cdp entries displayed : 4
```
Expected return data:
```python
{
    "cdp": {
        "index": {
            1: {
                "capability": "R I",
                "device_id": "R1.cisco.com",
                "hold_time": 169,
                "local_interface": "GigabitEthernet0/2/0",
                "platform": "ASR1002",
                "port_id": "GigabitEthernet0/0/0",
            },
            2: {
                "capability": "R B S",
                "device_id": "R2.cisco.com",
                "hold_time": 167,
                "local_interface": "GigabitEthernet0/2/2",
                "platform": "CISCO2951",
                "port_id": "GigabitEthernet0/0",
            },
            3: {
                "capability": "R I",
                "device_id": "R3.cisco.com",
                "hold_time": 165,
                "local_interface": "Multilink3",
                "platform": "ASR1002",
                "port_id": "Multilink1",
            },
            4: {
                "capability": "R I",
                "device_id": "R4.cisco.com",
                "hold_time": 160,
                "local_interface": "Ser 0/1/0:0",
                "platform": "ISR4451-X",
                "port_id": "Ser 0/1/0:0",
            },
        },
        "total_entries": 4,
    },
}

```
Actual (incorrect) return data:
```python
{
    'cdp': {
        'index': {
            1: {
                'capability': 'R I',
                'device_id': 'R1.cisco.com',
                'hold_time': 169,
                'local_interface': 'GigabitEthernet0/2/0',
                'platform': 'ASR1002',
                'port_id': 'GigabitEthernet0/0/0',
            },
            2: {
                'capability': 'R B S',
                'device_id': 'R2.cisco.com',
                'hold_time': 167,
                'local_interface': 'GigabitEthernet0/2/2',
                'platform': 'CISCO2951',
                'port_id': 'GigabitEthernet0/0',
            },
            3: {
                'capability': 'R I',
                'device_id': 'R3.cisco.com',
                'hold_time': 165,
                'local_interface': 'Multilink3',
                'platform': 'ASR1002',
                'port_id': 'Multilink1',
            },
            4: {
                'device_id': 'R4.cisco.com',
            },
        },
        'total_entries': 4,
    },
}
```

**Comment by SohanTirpude** [comment] 2024-04-29 17:11
Hello @ChristopherJHart,

From the expected and actual output, it looks like the issue is with the `device_id` as well as not able to proper output properly. In this specific case, index `4` is not populated properly.

Kindly correct me if I am wrong.

Also, can you re-try again after executing below command:

```
terminal width 0
terminal height 0
```
Because it looks like the output is getting printed on separate line and this may be causing this issue. Can you please try and let me know.

Thank you.

**Comment by ChristopherJHart** [comment] 2024-04-29 17:23
Hi @SohanTirpude - I'm not sure I follow, the output I posted looks properly formatted to me and matches what is present in the CLI after hostnames are sanitized.

**Comment by ChristopherJHart** [comment] 2024-04-30 12:14
Hi @Harishv01 - I have also reverified, and the above output *is* formatted correctly. Even with `terminal width 0` (`terminal height 0` is not a valid command).

I see the behavior you're describing on a Catalyst 8000v, but I do not see the behavior on real devices. Please test with real devices.

**Comment by Harishv01** [comment] 2024-05-03 09:02
```
expected_output = {
    "cdp": {
        "index": {
            1: {
                "device_id": "R1.cisco.com",
                "local_interface": "GigabitEthernet0/2/0",
                "hold_time": 169,
                "capability": "R I",
                "platform": "ASR1002",
                "port_id": "GigabitEthernet0/0/0"
            },
            2: {
                "device_id": "R2.cisco.com",
                "local_interface": "GigabitEthernet0/2/2",
                "hold_time": 167,
                "capability": "R B S",
                "platform": "CISCO2951",
                "port_id": "GigabitEthernet0/0"
            },
            3: {
                "device_id": "R3.cisco.com",
                "local_interface": "Multilink3",
                "hold_time": 165,
                "capability": "R I",
                "platform": "ASR1002",
                "port_id": "Multilink1"
            },
            4: {
                "device_id": "R4.cisco.com",
                "local_interface": "Ser0/1/0:0",
                "hold_time": 160,
                "capability": "R S I",
                "platform": "ISR4451-X",
                "port_id": "Ser0/1/0:0"
            }
        },
        "total_entries": 4
    }
}
```

I have raised a PR for your issue and the output looks like the above. Please check and let me know in case of any queries. If everything is good, I will merge the PR.

**Comment by ChristopherJHart** [comment] 2024-05-10 15:46
Hi @Harishv01 - that expected output looks good to me. Quick question - do we have any intent to expand shortened serial interface names (e.g. `Ser0/1/0:0`) to long-form names (e.g. `Serial0/1/0:0`) the same way we currently do for physical interfaces (e.g. `Gi0/0/0` -> `GigabitEthernet0/0/0`)?

**Comment by Harishv01** [comment] 2024-05-17 06:58
The PR has been merged and this fix will be available in the next version of pyats, i.e. 24.5. Hence, I am closing this ticket.

Thank you.

**Closed by Harishv01** 2024-05-17 06:58 UTC
