### ISSUE TITLE
[IOS]  [interface - learn] broken _IP helper parsing issue 

### ISSUE THREAD

**Issue by dan-md** [CiscoTestAutomation/genieparser#268] opened 2020-09-28 10:00 UTC
Hello team,

While I;m tring to learn feture 'interface', I'm getting the following error.

CODE:
ios01 = testbed.devices['tdit01']
ios01.connect()

interfaces = ios01.learn('interface')

===========================
ios int cfg:
interface Vlan65
 bandwidth 1000
 ip address 10.2.2.1 255.255.255.0
 ip helper-address 10.1.100.1
 no ip redirects
 no ip unreachables
 no ip proxy-arp
 standby 65 ip 10.2.2.254
 standby 65 priority 255
 standby 65 preempt

Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 244, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaTypeError: Vlan65.helper_address: Expected type '<class 'list'>' but got type '10.100.68.100'(<class 'str'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/netDevOps/networking/network_profile/corp/test01.py", line 10, in <module>
    interfaces = ios01.learn('interface')
  File "src/genie/conf/base/device.py", line 626, in genie.conf.base.device.Device.learn
  File "/srv/netDevOps/py3-venv2/lib/python3.6/site-packages/genie/libs/ops/interface/iosxe/interface.py", line 346, in learn
    self.make(final_call=True)
  File "/srv/netDevOps/py3-venv2/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 306, in genie.metaparser._metaparser.MetaParser.parse
Exception: Parser ShowIpInterface schema checking failed

**Comment by thaixuann** [comment] 2020-09-28 15:09
Hi @dan-md , 
Thanks reporting the issue.
Could you please send the full device output pyats-support-ext@cisco.com?

Thanks,
--Thai.

**Comment by dan-md** [comment] 2020-09-29 08:40
Thank you Thai!
Data was sent... let me know if anything else is required.

Kind regards,
Dan

**Comment by thaixuann** [comment] 2020-09-29 20:32
Thanks @dan-md for the outputs. I will work on it and let you know once the issue is fixed.

--Thai.

**Comment by thaixuann** [comment] 2020-09-30 22:17
Hello @dan-md ,
Could you please check to see what version of parser do you have?

`pip list | egrep "ats|genie"`

I ran interface vlan65 on my parser. It parsed as epxected. I am running with parser v20.9.

```
pip list | egrep genie.libs.parser
genie.libs.parser             20.9  
```

Thanks,
--Thai.

**Comment by dan-md** [comment] 2020-10-01 07:18
Hi Thai,

I was running 20.8 ...
Yes, with 20.9 it's working!.

The most interesting I did Update before opening issues and 20.8 was
installed, not 20.9..

Thank you!

Kind regards,
Dan Gaviuc

**Comment by thaixuann** [comment] 2020-10-01 15:03
Thanks @dan-md for the updates.
I will close this issue for now. 

--Thai.

**Closed by thaixuann** 2020-10-01 15:03 UTC
