### ISSUE TITLE
Show policy-map interface output failing on interface with no policy

### ISSUE THREAD

**Issue by MikeJames15** [CiscoTestAutomation/genieparser#55] opened 2019-10-31 18:59 UTC
I'm seeing this for an interface on which VLANs are defined and policies are applied on those VLANs. Not sure if that is why the interface name appears even though it has no policy configuration applied to it directly.

The error generated is:

       File "src/genie/conf/base/device.py", line 498, in genie.conf.base.device.Device.parse
       File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
       File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
       File "src/genie/metaparser/util/schemaengine.py", line 392, in genie.metaparser.util.schemaengine.Schema.validate
     genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['TenGigabitEthernet0/3/0', 'service_policy']]

The command output that generates the error is:

      TenGigabitEthernet0/3/0 
      TenGigabitEthernet0/3/0.nnnn 
     
       Service-policy output: xxxxx

If TenGigabitEthernet0/3/0 is removed from the command output, the output is parsed correctly.

**Comment by thaixuann** [comment] 2019-10-31 19:41
Thanks @MikeJames15 . Wil look into and let you know once the issue is fixed.

--Thai.

**Comment by thaixuann** [comment] 2019-11-06 18:43
Hello @MikeJames15 ,
Would you please provide the full output from the device for this command so that we can see if there is anything else we missed? Please send the output to pyats-support-ext@cisco.com.

Thanks,
--Thai.

**Comment by thaixuann** [comment] 2019-11-27 22:32
We fixed this issue. A pyats and genie package v19.11 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install --upgrade pyats
pip install --upgrade genie

Please let us know if you have question.

Thanks,
--Thai.

**Comment by MikeJames15** [comment] 2019-11-28 16:14
Thai,
               I tried the upgrade to v19.11. The upgrade went fine, but now when I try to run my code, I get the following error:
  File "/usr/local/lib/python3.6/dist-packages/genie/conf/__init__.py", line 19, in <module>
    from .main import Genie
  File "src/genie/conf/main.py", line 4, in init genie.conf.main
  File "/usr/local/lib/python3.6/dist-packages/genie/conf/base/__init__.py", line 4, in <module>
    from .device import Device
  File "src/genie/conf/base/device.py", line 11, in init genie.conf.base.device
ImportError: cannot import name get_parser_commands

When I try to import the Device with the line:
from genie.conf.base import Device

So I haven’t managed to test this. Should I modify my import?
Here is the full list of genie/pyats imports I am using in this class:
import genie.libs.parser
from genie.libs.parser.utils import get_parser
from genie.conf.base import Device
from pyats.datastructures import AttrDict
from genie.metaparser.util.schemaengine import Any, Optional

Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by MikeJames15** [comment] 2019-11-29 14:35
Thai,
               I have an additional sporadic issue but I’m not sure if it is related to the way in which I’m using genie. I’m running genie/pyats in Cisco NSO to parse the operational data commands. So the python vm is started by NSO and I’m not sure if there might be some peculiarities there. This is why I didn’t just open an issue for it. If you think I should, I will.

In the beginning I was getting it all the time then it happened off and on and now I haven’t seen it for a while. I was getting the following error of the first execution but the second time it always worked.
No such attribute in abstraction package 'genie.libs.parser': 'genie.libs.parser.show_bgp'

Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by jeaubin** [comment] 2019-11-29 16:10
@MikeJames15  - 

In [1]: from genie.libs.parser.utils import get_parser
In [2]:
It still works as expected, 

In [2]: import genie.libs.parser
   ...: from genie.libs.parser.utils import get_parser
   ...: from genie.conf.base import Device
   ...: from pyats.datastructures import AttrDict
   ...: from genie.metaparser.util.schemaengine import Any, Optional
   ...:
In [3]:

Can you make sure that all your packages are update to 19.11

pip list | grep genie 
pip list | grep pyats

If you want to debug this, you could come to our Webex team, and I'll be happy to help you to debug it with you: https://eurl.io/#r18UzrQVr

**Comment by jeaubin** [comment] 2019-11-29 16:12
Regarding 

No such attribute in abstraction package 'genie.libs.parser': 'genie.libs.parser.show_bgp'

Is it possible you have changed the OS of the device. We see this error when our "abstraction" library cannot find a specific implementation for that OS.

Let us know

**Comment by MikeJames15** [comment] 2019-11-29 16:19
JB,
               I don’t think that is the issue. The device os is in code. For practical purposes it is as if it were hardcoded and the first execution fails while the following ones work fine.
Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by MikeJames15** [comment] 2019-11-29 19:10
JB,
               Here you have the versions of the installed packages for genie and pyats:
pip3 list | grep genie
genie (19.11)
genie.abstract (19.11)
genie.conf (19.11)
genie.harness (19.11)
genie.libs.conf (19.11)
genie.libs.filetransferutils (19.11)
genie.libs.ops (19.11)
genie.libs.parser (19.11)
genie.libs.robot (19.7)
genie.libs.sdk (19.11)
genie.libs.telemetry (19.11)
genie.metaparser (19.11)
genie.ops (19.11)
genie.parsergen (19.11)
genie.predcore (19.11)
genie.telemetry (19.11)
genie.trafficgen (19.11)
genie.utils (19.11)

pip3 list | grep pyats
pyats (19.11)
pyats.aereport (19.11)
pyats.aetest (19.11)
pyats.async (19.11)
pyats.connections (19.11)
pyats.datastructures (19.11)
pyats.easypy (19.11)
pyats.kleenex (19.11)
pyats.log (19.11)
pyats.reporter (19.11)
pyats.results (19.11)
pyats.robot (19.7)
pyats.tcl (19.11)
pyats.topology (19.11)
pyats.utils (19.11)

So robot (pyats.robot and genie.libs.robot) are the only ones that ar not on 19.11. Instead they are at 19.7.
Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by MikeJames15** [comment] 2019-12-02 16:01
Hi,
               Today I tried upgrading again to see if there was any new code. Pyats did not download anything new, but genie package did download a whole bunch of packages. I tried the installation as root and as a regular user. As root I had no trouble installing the new packages, but as the regular user I got a segmentation fault. I am running the parsing as the regular user.
The error I’m getting now when parsing is:

  File "/home/mike/code/bluefringe/state/packages-in-use/1/genieparser/python/geniewrapper/geniewrapper.py", line 7, in <module>
    from genie.libs.parser.utils import get_parser
  File "/home/mike/.local/lib/python3.6/site-packages/genie/libs/parser/__init__.py", line 16, in <module>
    from .base import tcl_invoke_ats_cmd,\
  File "/home/mike/.local/lib/python3.6/site-packages/genie/libs/parser/base.py", line 17, in <module>
    from genie.metaparser import MetaParser
  File "/home/mike/.local/lib/python3.6/site-packages/genie/metaparser/__init__.py", line 7, in <module>
    from ._metaparser import *
  File "src/genie/metaparser/_metaparser.py", line 11, in init genie.metaparser._metaparser
  File "/home/mike/.local/lib/python3.6/site-packages/unicon/__init__.py", line 16, in <module>
    __plugin_manager__.discover_builtin_plugins()
  File "src/unicon/core/pluginmanager.py", line 263, in unicon.core.pluginmanager.PluginManager.discover_builtin_plugins
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mike/.local/lib/python3.6/site-packages/unicon/plugins/iosxe/csr1000v/service_statements.py", line 4, in <module>
    from .patterns import Csr1000vPatterns
ImportError: cannot import name 'Csr1000vPatterns'

Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by simingy** [comment] 2019-12-02 18:59
this is because of https://github.com/pypa/pip/issues/7408

`pip uninstall unicon unicon.plugins`
and
`pip install unicon` 

should fix it for now

**Comment by MikeJames15** [comment] 2019-12-03 15:14
Siming,
               I am now getting the following error on the parsing call:
  File "/home/mike/code/bluefringe/state/packages-in-use/1/genieparser/python/geniewrapper/geniewrapper.py", line 181, in parse_output
    return (device.parse(parser_cmd, output=device_output), schema)
  File "src/genie/conf/base/device.py", line 536, in genie.conf.base.device.Device.parse
  File "/usr/local/lib/python3.6/dist-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1271, in cli
    return super().cli(output=show_output)
  File "/usr/local/lib/python3.6/dist-packages/genie/libs/parser/iosxe/show_policy_map.py", line 941, in cli
    class_map_dict['queue_limit_packets'] = m.groupdict()['queue_limit']
UnboundLocalError: local variable 'class_map_dict' referenced before assignment

Looking at the source for show_policy_map.py source code, the class_map_dict keys are assigned, but the dict is never instantiated.
Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by thaixuann** [comment] 2019-12-03 18:05
Hello Michael,
Could you please provide the device outputs that gave you this error so that we can fix the issue? Please send the output to pyats-support-ext@cisco.com<mailto:pyats-support-ext@cisco.com>.


Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by MikeJames15** [comment] 2019-12-04 16:46
Thai,
               Thanks for your response. I don’t believe this error is data dependent.
I downloaded the source and run a make deploy for the parser package.
Then added
class_map_dict = {}
at genieparser/src/genie/libs/parser/iosxe/show_policy_map.py line 389 in  and that fixed the issue. The problem is that the code is trying to assign entries in the dict the the dict is not created before adding the entries.
Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by thaixuann** [comment] 2019-12-04 17:20
Hi Michael,

Thanks to confirm, though we would like to confirm all is working as expected.

This parser currently work with outputs that we have in our device, so even though fixing the dictionary is the right approach, we would like to verify to make sure all other outputs is parsed correctly.

If you can’t provide, that’s fine and we will just do that fix.


Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by MikeJames15** [comment] 2019-12-04 22:35
Thai,
         This is the output we’re working with:
TenGigabitEthernet0/0/0

  Service-policy output: queuing

    queue stats for all priority classes:
      Queueing
      queue limit 512 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0

    Class-map: class1 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp ef (46)
      Priority: Strict, b/w exceed drops: 0


    Class-map: class2 (match-any)
      375750 packets, 34472240 bytes
      1 minute offered rate 3000 bps, drop rate 0000 bps
      Match: ip dscp cs6 (48) cs7 (56)
      Queueing
      queue limit 41666 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 295079/25921114
      bandwidth remaining 5%

    Class-map: class3 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp af31 (26) af32 (28)
      Queueing
      queue limit 41666 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0
      bandwidth remaining 25%

    Class-map: class4 (match-any)
      23354 packets, 5387547 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp af21 (18) af22 (20)
      Queueing
      queue limit 41666 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 23354/5387547
      bandwidth remaining 25%

    Class-map: class4 (match-any)
      1079724 packets, 72717061 bytes
      1 minute offered rate 8000 bps, drop rate 0000 bps
      Match: any
      Queueing
      queue limit 41666 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 1026702/51418238
      bandwidth remaining 25%
TenGigabitEthernet0/0/1

  Service-policy output: queuing

    queue stats for all priority classes:
      Queueing
      queue limit 512 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0

    Class-map: class1 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp ef (46)
      Priority: Strict, b/w exceed drops: 0


    Class-map: class2 (match-any)
      137136 packets, 11102652 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp cs6 (48) cs7 (56)
      Queueing
      queue limit 13932 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 67136/5486642
      bandwidth remaining 5%

    Class-map: class3 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp af31 (26) af32 (28)
      Queueing
      queue limit 13932 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0
      bandwidth remaining 25%

    Class-map: class4 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp af21 (18) af22 (20)
      Queueing
      queue limit 13932 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0
      bandwidth remaining 25%

    Class-map: class5 (match-any)
      22860 packets, 9130346 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: any
      Queueing
      queue limit 13932 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
     (pkts output/bytes output) 272/20774
      bandwidth remaining 25%
TenGigabitEthernet0/0/2

Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by thaixuann** [comment] 2019-12-05 01:58
Thanks for the output Michael. We’ll let you know once the issue is fixed.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by MikeJames15** [comment] 2019-12-05 18:15
Thai,
               How’s it going? I was looking at the output generated for this command for the section that was added (queue stats for all priority classes) and see that the Queueing and queue limit lines are not getting parsed into the output.

Here’s the relevant data that I parsed:

TenGigabitEthernet0/0/0

  Service-policy output: queuing

    queue stats for all priority classes:
      Queueing
      queue limit 512 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 0/0

    Class-map: class1 (match-any)
      0 packets, 0 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: ip dscp ef (46)
      Priority: Strict, b/w exceed drops: 0

…

And here is the corresponding output obtained:

parsed_output: {'TenGigabitEthernet0/1/0': {'service_policy': {'output': {'policy_name': {'queuing': {'queue_stats_for_all_priority_classes': {'priority_level': {'default': {'queue_depth': 0, 'total_drops': 0, 'no_buffer_drops': 0, 'pkts_output': 0, 'bytes_output': 0}}},  'class_map': {'class1': {'match_evaluation': 'match-any', 'packets': 0, 'bytes': 0, 'rate': {'interval': 60, 'offered_rate_bps': 0, 'drop_rate_bps': 0}, 'match': ['ip dscp ef (46)']},  …

I do see the “Queueing” and “queue limit” parsed for regular class maps but not for the “all classes“ class map.
Best regards and thanks for the quick responses,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by thaixuann** [comment] 2019-12-05 20:51
Thanks Michael for letting us know. I will take a look this un-parsed issue as well.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment] 2019-12-06 00:21
Hello Mike,
Just wanted to confirm,  you opened 3 GitHub cases. Both https://github.com/CiscoTestAutomation/genieparser/issues/54 and https://github.com/CiscoTestAutomation/genieparser/issues/55 are the same and you had provided us with the device outputs and we are working on that.
For https://github.com/CiscoTestAutomation/genieparser/issues/61, could you please check to see if you are still having issue? if you are, can you please provide the device output for issue #61?

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment] 2020-01-08 17:05
Hello @MikeJames15 
Sorry for the delays

We are having 2 issues with the outputs provided:

1) The interface for of the output doesn't seem to have issue or error as you described:
	provided output with interface: **TenGigabitEthernet0/0/0**
	provided error output interface: **TenGigabitEthernet0/1/0**
2) The class map name is duplicated:

Class-map: **class4** (match-any)
23354 packets, 5387547 bytes
1 minute offered rate 0000 bps, drop rate 0000 bps
Match: ip dscp af21 (18) af22 (20)
Queueing
queue limit 41666 packets
(queue depth/total drops/no-buffer drops) 0/0/0
(pkts output/bytes output) 23354/5387547
bandwidth remaining 25%

Class-map: **class4** (match-any)
1079724 packets, 72717061 bytes
1 minute offered rate 8000 bps, drop rate 0000 bps
Match: any
Queueing
queue limit 41666 packets
(queue depth/total drops/no-buffer drops) 0/0/0
(pkts output/bytes output) 1026702/51418238
bandwidth remaining 25%
TenGigabitEthernet0/0/1

Can you please check and help us verify?

Thanks,

--Thai.

**Comment by thaixuann** [comment] 2020-01-29 23:28
Hello @MikeJames15 ,
Any update on this?

Thanks,
--Thai.

**Closed** 2020-02-20 14:49 UTC
Labels: bug
