### ISSUE TITLE
problem with show interface {{interface}} on NXOS 

### ISSUE THREAD

**Issue by from88** [CiscoTestAutomation/genieparser#839] opened 2024-04-03 21:02 UTC
hello, seems like pyats genie model 'show interface {interface}' doesn't recognize and breaks when NX-OS has interface with status like this:

```
CBCNET02A# show  interface ethernet 199/1/2
Ethernet199/1/2 is down (Disabled by Server Mgr)
admin state is up,
  Belongs to Po3902
  Hardware: 1000/10000 Ethernet, address: 54a2.74f9.8343 (bia 54a2.74f9.83
43)
```

`FAILED! => {"changed": false, "msg": "The pyats library return an error for 'show interface ethernet199/1/2' for 'nxos'. Error: 'ethernet199/1/2'."}`

 I think it's because of quite unusual port status.

**Comment by Harishv01** [comment] 2024-04-04 10:10
Hi,

Kindly give me some time i will check and get back to you

Thank you

**Comment by SohanTirpude** [comment] 2024-04-10 09:10
Hello @from88,

Is there any update on this?

Thank you.

**Comment by from88** [comment] 2024-04-10 10:16
Hello, is there more insteuction how to do  that ? Because im not using PyAts itself, im just using the genie parser with ansible.

**Comment by SohanTirpude** [comment] 2024-04-11 17:02
Hello @from88,

I am not sure about ansible. I think you will have to run with pyats only. By the way, is this the correct command `show  interface ethernet 199/1/2`? Or should it be like this: `show interface ethernet199/1/2`?

Kindly let me know.

**Comment by Harishv01** [comment] 2024-04-15 14:05
Hi,

I am not sure about ansible. I think you will have to run with pyats only. By the way, is this the correct command show  interface ethernet 199/1/2? Or should it be like this: show interface ethernet199/1/2?

Kindly let me know.

**Comment by from88** [comment] 2024-04-16 10:21
> Hi,
> 
> I am not sure about ansible. I think you will have to run with pyats only. By the way, is this the correct command show interface ethernet 199/1/2? Or should it be like this: show interface ethernet199/1/2?
> 
> Kindly let me know.

it works both ways `show interface ethernet199/1/2` and `show interface ethernet 199/1/2`

**Comment by Harishv01** [comment] 2024-04-16 16:58
Please execute the command `terminal length 0` or `terminal length 0` in your terminal. This is necessary because your window is smaller and the output is splitting into two lines.
Hardware: 1000/10000 Ethernet, address: 54a2.74f9.8343 (bia 54a2.74f9.83
43)
After running the terminal commands, try again. If it still doesn't work, please share the proper output.

**Comment by from88** [comment] 2024-04-16 17:52
this week that `error` state changed to the normal one. So i can't reproduce it anymore.. But the case is still legit.
Should i close the topic ?

**Comment by Harishv01** [comment] 2024-04-17 07:59
If the error state has changed to the normal one and you're unable to reproduce the issue anymore, it's a good indication that the problem has been resolved.Hence,I am closing the ticket

**Closed by Harishv01** 2024-04-17 07:59 UTC
