### ISSUE TITLE
local variable 'neighbors_dict' referenced before assignment - Failed to parse command output 

### ISSUE THREAD

**Issue by som-shekhar** [CiscoTestAutomation/genieparser#548] opened 2021-09-29 11:08 UTC
Hi
I am trying to parse the following ospf contents using the following task:

```

  OSPFv3 1 address-family ipv4 (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:32    103             Vlan443
10.180.225.1      0   FULL/  -        00:00:38    107             Vlan447

          OSPFv3 1 address-family ipv6 (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:38    103             Vlan443
10.180.225.1      0   FULL/  -        00:00:38    107             Vlan447

          OSPFv3 1 address-family ipv4 vrf vrf-comm (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:35    104             Vlan444
10.180.225.1      0   FULL/  -        00:00:35    108             Vlan448

          OSPFv3 1 address-family ipv6 vrf vrf-comm (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:39    104             Vlan444
10.180.225.1      0   FULL/  -        00:00:34    108             Vlan448

          OSPFv3 1 address-family ipv4 vrf vrf-gs (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:39    102             Vlan442
10.180.225.1      0   FULL/  -        00:00:39    106             Vlan446

          OSPFv3 1 address-family ipv6 vrf vrf-gs (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:36    102             Vlan442
10.180.225.1      0   FULL/  -        00:00:37    106             Vlan446

          OSPFv3 1 address-family ipv4 vrf vrf-ss (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:39    101             Vlan441
10.180.225.1      0   FULL/  -        00:00:38    105             Vlan445

          OSPFv3 1 address-family ipv6 vrf vrf-ss (router-id 10.180.225.102)

Neighbor ID     Pri   State           Dead Time   Interface ID    Interface
10.180.225.2      0   FULL/  -        00:00:37    101             Vlan441
10.180.225.1      0   FULL/  -        00:00:37    105             Vlan445
```

```
- name: "show ospv3   summary"
  set_fact:
    ospvf: "{{ file_contents | parse_genie(command='show ospfv3 neighbor', os='iosxr') }}"
  delegate_to: localhost
```

![image](https://user-images.githubusercontent.com/5188091/135256892-a278c21d-2bbc-4c18-a00c-bf9eed5a9868.png)

**Comment by ThomasJRyan** [comment] 2021-10-01 19:28
This is typically caused by a regex not being matched as it should be. For bugs like this we like to offer them up to the community to fix. I can look into it, though I can't guarantee when I can get a patch ready. If you are willing, we would be delighted if you could look into resolving this issue and creating a PR for it

**Comment by ThomasJRyan** [comment] 2021-11-22 14:31
No response from user. Closing

**Closed** 2021-11-22 14:31 UTC
