### ISSUE TITLE
junos "show interface" is missing the description field 

### ISSUE THREAD

**Issue by klbnet** [CiscoTestAutomation/genieparser#371] opened 2020-12-31 06:50 UTC
junos "show interface" is missing the description field from the physical interfaces. Thank you. 

Sample Raw: 
    "stdout_lines": [
        [
            "Physical interface: em0, Enabled, Physical link is Up",
            "  Interface index: 8, SNMP ifIndex: 17",
            "  Description: ADMIN|MGMT|DEVICE",
            "  Type: Ethernet, Link-level type: Ethernet, MTU: 1514, Speed: 1000mbps",
            "  Device flags   : Present Running",
            "  Interface flags: SNMP-Traps",
            "  Link type      : Full-Duplex",

Sample parsed: 

    "ansible_facts": {
        "pyats_int": {
            "interface-information": {
                "physical-interface": [
                    {
                        "admin-status": {
                            "@junos:format": "Enabled"
                        },
                        "current-physical-address": "84:03:28:ee:89:00",
                        "hardware-physical-address": "84:03:28:ee:89:00",
                        "if-config-flags": {
                            "iff-snmp-traps": true
                        },
                        "if-device-flags": {
                            "ifdf-present": true,
                            "ifdf-running": true
                        },
                        "interface-flapped": {
                            "#text": "2020-12-30 21:56:31 UTC (08:46:10 ago)"
                        },
                        "link-level-type": "Ethernet",
                        "link-type": "Full-Duplex",
                        "logical-interface": [
                            {
                                "address-family": [
                                    {
                                        "address-family-flags": {
                                            "ifff-is-primary": true
                                        },
                                        "address-family-name": "inet",
~cut~

**Comment by tahigash** [comment] 2021-01-01 10:25
@klbnet I checked the regex for description, but it seems fine. could you please send the whole show output from device to pyats-support-ext@cisco.com?

**Comment by klbnet** [comment] 2021-01-04 15:42
@tahigash thank you for replying and apologies for my late reply. I found the regex for description and they rely on \S+ . When I smoothed over my description to paste, I removed some white space from the middle. 
After testing, it seems the whitespace is causing the description not to show in the pyats output. 
Is this something fixable in pyats? 

Example: 
et-0/1/0        up    down TEST-DESC:1|TEST#1234 DEV

**Comment by tahigash** [comment] 2021-01-04 16:47
@klbnet thanks for sharing the cause due to space in description. I internally fixed the parser. The fix will be ready at end of Jan as official package.

Let me know if you need the fix in advance. I will release beta package for you.

**Comment by klbnet** [comment] 2021-01-04 16:49
I would love in advance, but as a newbie I am not sure how to switch between beta and prod releases? 
Thank you for the quick turn around and Happy new year!

**Comment by tahigash** [comment] 2021-01-04 21:12
@klbnet yeah, happy new year! beta package can be upgraded by `--upgrade` and `--pre` options.

Please upgrade parser library like below.
```
pip install genie.libs.parser --upgrade --pre
```
if your pyATS is not 20.12 yet, please upgrade to 20.12 first by below command.
```
pyats version update
```

beta package is released, so closing this issue. feel free to reopen if same issue.

**Closed by tahigash** 2021-01-04 21:12 UTC
