### ISSUE TITLE
Parse Failure on LLDP neighbor detail

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genieparser#20] opened 2019-06-27 15:27 UTC
Someone made an issue on my Ansible parse_genie module, but I think they may have found a parse issue in the genie parser. [Here](https://github.com/clay584/parse_genie/issues/1) is the original issue.

It looks like `System Description` data in `show lldp neighbor detail` is possibly failing to parse therefore `system_description` is not in the parsed output.

See [this](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_lldp.py#L157) for more info.

**Comment by jeaubin** [comment] 2019-06-27 16:51
Thanks to report that one,  seems to be an issue with the parser/different image. 

We are on it.

**Comment by jeaubin** [comment] 2019-07-11 17:18
It has been fixed, and a beta package has been released

pip install genie.lis.parser --upgrade --pre

Give it a try and let us know.

Thanks

**Comment by jeaubin** [comment] 2019-07-12 13:15
Closing as it was confirmed it works as expected here: https://github.com/clay584/parse_genie/issues/1

**Closed by jeaubin** 2019-07-12 13:15 UTC
