### ISSUE TITLE
Section of "policy-map interface output" command not getting parsed

### ISSUE THREAD

**Issue by MikeJames15** [CiscoTestAutomation/genieparser#158] opened 2020-05-22 19:47 UTC
The early random detect table in the show policy-map interface output does not seem to be getting parsed. The output I parsed was the following:
`
GigabitEthernet0/0/3.3001 

  Service-policy output: policy1

    Class-map: class-default (match-any)  
      3275598 packets, 362268259 bytes
      1 minute offered rate 0000 bps, drop rate 0000 bps
      Match: any 
      Queueing
      queue limit 208 packets
      (queue depth/total drops/no-buffer drops) 0/0/0
      (pkts output/bytes output) 3022920/263471161
      bandwidth remaining ratio 1 
      Overhead Accounting enabled
      shape (average) cir 50000000, bc 200000, be 200000
      target shape rate 50000000
       Overhead Accounting Enabled

      Service-policy : policy2 

        Class-map: cm1 (match-any)  
          3000453 packets, 262033259 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match: access-group name accssgroup1
          Queueing
          queue limit 525000 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 3000454/262033337
          bandwidth remaining 1%
          Overhead Accounting enabled
            Exp-weight-constant: 9 (1/512)
            Mean queue depth: 94 bytes
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            cs6      3000454/262033337       0/0              0/0             225750        262500  1/10
          
          QoS Set
            dscp cs6
              Marker statistics: Disabled

        Class-map: cm2 (match-any)  
          0 packets, 0 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match:  dscp af41 (34) af42 (36)
          Queueing
          queue limit 312500 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 0/0
          bandwidth remaining 25%
          Overhead Accounting enabled
          
          QoS Set
            dscp af41
              Marker statistics: Disabled

        Class-map: cm3 (match-any)  
          0 packets, 0 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match: ip dscp af31 (26) af32 (28)
          Match:  dscp af31 (26) af32 (28)
          Queueing
          queue limit 312500 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 0/0
          bandwidth remaining 10%
          Overhead Accounting enabled
            Exp-weight-constant: 9 (1/512)
            Mean queue depth: 0 bytes
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            af31           0/0               0/0              0/0             134375        156250  1/10
          
          QoS Set
            dscp af31
              Marker statistics: Disabled

        Class-map: cm4 (match-any)  
          0 packets, 0 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match: ip dscp af21 (18) af22 (20)
          Match:  dscp af21 (18) af22 (20)
          Queueing
          queue limit 312500 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 0/0
          bandwidth remaining 40%
          Overhead Accounting enabled
            Exp-weight-constant: 9 (1/512)
            Mean queue depth: 0 bytes
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            af21           0/0               0/0              0/0             134375        156250  1/10
          
          QoS Set
            dscp af21
              Marker statistics: Disabled

        Class-map: cm5 (match-any)  
          0 packets, 0 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match:  dscp af11 (10) af12 (12)
          Queueing
          queue limit 312500 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 0/0
          bandwidth remaining 5%
          Overhead Accounting enabled
            Exp-weight-constant: 9 (1/512)
            Mean queue depth: 0 bytes
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            af11           0/0               0/0              0/0              78125        156250  1/10
          
          QoS Set
            dscp af11
              Marker statistics: Disabled

        Class-map: class-default (match-any)  
          275144 packets, 100234922 bytes
          1 minute offered rate 0000 bps, drop rate 0000 bps
          Match: any 
          Queueing
          queue limit 312500 bytes
          (queue depth/total drops/no-buffer drops) 0/0/0
          (pkts output/bytes output) 22466/1437824
          bandwidth remaining 19%
          Overhead Accounting enabled
            Exp-weight-constant: 9 (1/512)
            Mean queue depth: 64 bytes
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            default    22466/1437824         0/0              0/0             115625        156250  1/10
          
          QoS Set
            dscp default
              Marker statistics: Disabled
`

The output generated was as follows:
`
    "GigabitEthernet0/0/3.3001": {
        "service_policy": {
            "output": {
                "policy_name": {
                    "policy1": {
                        "child_policy_name": {
                            "poicy2": {
                                "class_map": {
                                    "class-default": {
                                        "bandwidth_remaining_percent": 19,
                                        "bytes": 100234922,
                                        "bytes_output": 1437824,
                                        "match": [
                                            "any"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 275144,
                                        "pkts_output": 22466,
                                        "qos_set": {
                                            "dscp": {
                                                "default": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 312500,
                                        "queueing": true,
                                        "random_detect": {
                                            "exp_weight_constant": "9 (1/512)",
                                            "mean_queue_depth": 64
                                        },
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    },
                                    "cm1": {
                                        "bandwidth_remaining_percent": 1,
                                        "bytes": 262033259,
                                        "bytes_output": 262033337,
                                        "match": [
                                            "access-group name accessgroup1"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 3000453,
                                        "pkts_output": 3000454,
                                        "qos_set": {
                                            "dscp": {
                                                "cs6": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 525000,
                                        "queueing": true,
                                        "random_detect": {
                                            "exp_weight_constant": "9 (1/512)",
                                            "mean_queue_depth": 94
                                        },
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    },
                                    "cm3": {
                                        "bandwidth_remaining_percent": 10,
                                        "bytes": 0,
                                        "bytes_output": 0,
                                        "match": [
                                            "ip dscp af31 (26) af32 (28)",
                                            "dscp af31 (26) af32 (28)"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 0,
                                        "pkts_output": 0,
                                        "qos_set": {
                                            "dscp": {
                                                "af31": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 312500,
                                        "queueing": true,
                                        "random_detect": {
                                            "exp_weight_constant": "9 (1/512)",
                                            "mean_queue_depth": 0
                                        },
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    },
                                    "cm2": {
                                        "bandwidth_remaining_percent": 25,
                                        "bytes": 0,
                                        "bytes_output": 0,
                                        "match": [
                                            "dscp af41 (34) af42 (36)"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 0,
                                        "pkts_output": 0,
                                        "qos_set": {
                                            "dscp": {
                                                "af41": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 312500,
                                        "queueing": true,
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    },
                                    "cm4": {
                                        "bandwidth_remaining_percent": 40,
                                        "bytes": 0,
                                        "bytes_output": 0,
                                        "match": [
                                            "ip dscp af21 (18) af22 (20)",
                                            "dscp af21 (18) af22 (20)"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 0,
                                        "pkts_output": 0,
                                        "qos_set": {
                                            "dscp": {
                                                "af21": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 312500,
                                        "queueing": true,
                                        "random_detect": {
                                            "exp_weight_constant": "9 (1/512)",
                                            "mean_queue_depth": 0
                                        },
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    },
                                    "cm5": {
                                        "bandwidth_remaining_percent": 5,
                                        "bytes": 0,
                                        "bytes_output": 0,
                                        "match": [
                                            "dscp af11 (10) af12 (12)"
                                        ],
                                        "match_evaluation": "match-any",
                                        "no_buffer_drops": 0,
                                        "packets": 0,
                                        "pkts_output": 0,
                                        "qos_set": {
                                            "dscp": {
                                                "af11": {
                                                    "marker_statistics": "Disabled"
                                                }
                                            }
                                        },
                                        "queue_depth": 0,
                                        "queue_limit_bytes": 312500,
                                        "queueing": true,
                                        "random_detect": {
                                            "exp_weight_constant": "9 (1/512)",
                                            "mean_queue_depth": 0
                                        },
                                        "rate": {
                                            "drop_rate_bps": 0,
                                            "interval": 60,
                                            "offered_rate_bps": 0
                                        },
                                        "total_drops": 0
                                    }
                                }
                            }
                        },
                        "class_map": {
                            "class-default": {
                                "bandwidth": "remaining ratio 1",
                                "bytes": 362268259,
                                "bytes_output": 263471161,
                                "match": [
                                    "any"
                                ],
                                "match_evaluation": "match-any",
                                "no_buffer_drops": 0,
                                "packets": 3275598,
                                "pkts_output": 3022920,
                                "queue_depth": 0,
                                "queue_limit_packets": "208",
                                "queueing": true,
                                "rate": {
                                    "drop_rate_bps": 0,
                                    "interval": 60,
                                    "offered_rate_bps": 0
                                },
                                "shape_bc_bps": 200000,
                                "shape_be_bps": 200000,
                                "shape_cir_bps": 50000000,
                                "shape_type": "average",
                                "target_shape_rate": 50000000,
                                "total_drops": 0
                            }
                        }
                    }
                }
            }
        }
    }
`

The section that is missing in the output corresponds to the tables such as:

`
            dscp       Transmitted         Random drop      Tail drop          Minimum        Maximum     Mark
                    pkts/bytes            pkts/bytes       pkts/bytes          thresh         thresh     prob
                                                                              bytes         bytes
            cs6      3000454/262033337       0/0              0/0             225750        262500  1/10
`

This was parsed with genie version 20.2.

**Comment by lubnarasheed** [comment] 2020-05-25 13:21
Hi @MikeJames15,

Thanks for reporting this issue, genie.libs.parser has a newer version of the package (20.4)

Would it be possible for you to upgrade to version 20.4 and check if the issue is still seen?

Regards,
Lubna

**Comment by MikeJames15** [comment] 2020-05-26 19:00
Lubna,
               Hi how are you? Yesterday was a holiday in Argentina where I’m from so I wasn’t working. I have updated genie to version 20.4 and see the same output for the command.
Best regards,

__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by MikeJames15** [comment] 2020-05-26 19:16
Lubna,
               I looked at the source code and I think there is a problem with regular expression p27. I tried it on the output of the command and it didn’t match, but if I do the following modification:

579c579
<         p27 = re.compile(r'^ +(?P<class>(\w+)) +(?P<value1>([\d\/]+)) +(?P<value2>([\d\/]+)) +'
---
>         p27 = re.compile(r'^(?P<class>(\w+)) +(?P<value1>([\d\/]+)) +(?P<value2>([\d\/]+)) +'

Meaning allowing spaces at the beginning of the line, it does match the entries.
Best regards,
__

Michael James
Principal, Network Architecture

Rethink Possible®

AT&T Business Solutions – Systems Integrator Solutions
mj550x@intl.att.com<mailto:mj550x@intl.att.com>
(470) 277-6950

**Comment by lubnarasheed** [comment] 2020-05-26 22:48
Hi Mike,

Not a problem, thanks for sending me this output, I will fix the parser and update you

**Comment by lubnarasheed** [comment] 2020-10-08 01:15
Hi Mike,

Apologies for the delay in getting back to you on this. We've identified the issue and working to release a fix by the end of this week.

Regards,
Lubna Rasheed

**Comment by lubnarasheed** [comment] 2020-10-13 21:08
Hi @MikeJames15,

Could your please try the following beta package for genie.libs.parser and let us know if it resolves your issue?

https://pypi.org/project/genie.libs.parser/20.9.1b0/

This beta includes a fix for the regex that was not being parsed correctly.

I will go ahead and close this issue now. If the issue is still seen, please feel free to raise another issue on GitHub or email us at pyats-support-ext@cisco.com

Regards,
Lubna Rasheed

**Closed** 2020-10-13 21:09 UTC
