### ISSUE TITLE
IOSXE "show authentication sessions interface details" parser issues

### ISSUE THREAD

**Issue by ahlara-devcore** [CiscoTestAutomation/genieparser#457] opened 2021-05-27 17:56 UTC
Hi,

When I run the parser in the following output:

```
           Interface:  GigabitEthernet4/0/18
               IIF-ID:  0x273804C8
          MAC Address:  1062.e519.072e
         IPv6 Address:  Unknown
         IPv4 Address:  10.15.1.176
            User-Name:  J2XD0170154
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  in
      Session timeout:  64800s (server), Remaining: 40368s
       Timeout action:  Reauthenticate
  Acct update timeout:  300s (local), Remaining: 186s
    Common Session ID:  86010F8900002F28A5016B11
      Acct Session ID:  0x00003645
               Handle:  0x21000fc0
       Current Policy:  C3PL_ISE_210


Local Policies:
        Service Template: DEFAULT_LINKSEC_POLICY_SHOULD_SECURE (priority 150)
      Security Policy:  Should Secure

Server Policies:
              ACS ACL: xACSACLx-IP-PERMIT_ALL_IPV4_TRAFFIC-57f6b0d3
      Session-Timeout: 64800 sec


Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped
```
I get this error:

```
Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 252, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaTypeError: interfaces.GigabitEthernet4/0/18.mac_address.1062.e519.072e.session_timeout: Expected type '{'type': <class 'str'>, Optional  (str) timeout: <class 'str'>, Optional  (str) remaining: <class 'str'>}' but got type '64800 sec'(<class 'str'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 306, in genie.metaparser._metaparser.MetaParser.parse
Exception: Parser ShowAuthenticationSessionsInterface schema checking failed
```
I was able to track the problem to `p1.match(line)` section in show_authentication_sessions.py.
The line `Session-Timeout: 64800 sec` from the output is being passed to the schema as a value of the key `session_timeout`.

```
                        'session_timeout': {
                            'type': str,  # local, N/A
                            Optional('timeout'): str,
                            Optional('remaining'): str,
                        },
```

However, it should be assigned to `server_policies`
```
                        Optional('server_policies'): {
                            Any():{ # 1, 2, 3
                                Optional('name'): str,
                                Optional('policies'): str,
                                Optional('security_policy'): str,
                                Optional('security_status'): str
                            }
                        },
``` 
I think they problem is caused by `key = re.sub(r'( |-)', '_', group['argument'].lower())` which assigns the string `session_timeout` to the variable `key` when the argument is `Session-Timeout: 64800 sec`. This key will not allow the argument to be processed as a server policy property because it matches a value in the `known_list` variable.
Removing `session_timeout` from the `known_list` fixes my issue but I do not know if this will break the parser in another scenario.

**Comment by domachad** [comment] 2021-05-27 20:07
Hi @ahlara-devcore.
I could not reproduce your problem. Which version are you using?

Parsing the output you provided, I got the following:

{
    "interfaces": {
        "GigabitEthernet4/0/18": {
            "mac_address": {
                "1062.e519.072e": {
                    "ipv6_address": "Unknown",
                    "iif_id": "0x273804C8",
                    "ipv4_address": "10.15.1.176",
                    "user_name": "J2XD0170154",
                    "status": "Authorized",
                    "domain": "DATA",
                    "oper_host_mode": "multi-auth",
                    "oper_control_dir": "in",
                    "session_timeout": {
                        "type": "server",
                        "timeout": "64800s",
                        "remaining": "40368s"
                    },
                    "timeout_action": "Reauthenticate",
                    "common_session_id": "86010F8900002F28A5016B11",
                    "acct_session_id": "0x00003645",
                    "handle": "0x21000fc0",
                    "current_policy": "C3PL_ISE_210"
                }
            }
        }
    }
}

**Comment by ahlara-devcore** [comment] 2021-05-28 12:52
Hi @domachad,

I was using 21.4 and upgrad it to 21.5 with the same result.

The complete command output is:

```
dmf1#show authentication sessions interface Gi4/0/18 details
            Interface:  GigabitEthernet4/0/18
               IIF-ID:  0x2B5A8BE5
          MAC Address:  0800.273f.f427
         IPv6 Address:  fe80::7635:22a5:7597:2429
         IPv4 Address:  10.15.1.233
            User-Name:  08-00-27-3F-F4-27
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  in
      Session timeout:  N/A
  Acct update timeout:  300s (local), Remaining: 48s
    Common Session ID:  86010F8900002F29A505F344
      Acct Session ID:  0x00003487
               Handle:  0x73000fc1
       Current Policy:  C3PL_ISE_210


Local Policies:
        Service Template: DEFAULT_LINKSEC_POLICY_SHOULD_SECURE (priority 150)
      Security Policy:  Should Secure

Server Policies:
              ACS ACL: xACSACLx-IP-PERMIT_ALL_IPV4_TRAFFIC-57f6b0d3


Method status list:
       Method           State
        dot1x           Stopped
          mab           Authc Success

----------------------------------------

            Interface:  GigabitEthernet4/0/18
               IIF-ID:  0x273804C8
          MAC Address:  1062.e519.072e
         IPv6 Address:  Unknown
         IPv4 Address:  10.15.1.176
            User-Name:  J2XD0170154
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  in
      Session timeout:  64800s (server), Remaining: 24177s
       Timeout action:  Reauthenticate
  Acct update timeout:  300s (local), Remaining: 208s
    Common Session ID:  86010F8900002F28A5016B11
      Acct Session ID:  0x00003951
               Handle:  0x21000fc0
       Current Policy:  C3PL_ISE_210


Local Policies:
        Service Template: DEFAULT_LINKSEC_POLICY_SHOULD_SECURE (priority 150)
      Security Policy:  Should Secure

Server Policies:
              ACS ACL: xACSACLx-IP-PERMIT_ALL_IPV4_TRAFFIC-57f6b0d3
      Session-Timeout: 64800 sec


Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped
```
When I applied the change I described in my first post. I got this, which it should be the response.

```
{
  "interfaces": {
    "GigabitEthernet4/0/18": {
      "mac_address": {
        "0800.273f.f427": {
          "acct_session_id": "0x00003487",
          "common_session_id": "86010F8900002F29A505F344",
          "current_policy": "C3PL_ISE_210",
          "domain": "DATA",
          "handle": "0x73000fc1",
          "iif_id": "0x2B5A8BE5",
          "ipv4_address": "10.15.1.233",
          "ipv6_address": "fe80::7635:22a5:7597:2429",
          "local_policies": {
            "security_policy": "Should Secure",
            "template": {
              "DEFAULT_LINKSEC_POLICY_SHOULD_SECURE": {
                "priority": 150
              }
            }
          },
          "method_status": {
            "dot1x": {
              "method": "dot1x",
              "state": "Stopped"
            },
            "mab": {
              "method": "mab",
              "state": "Authc Success"
            }
          },
          "oper_control_dir": "in",
          "oper_host_mode": "multi-auth",
          "server_policies": {
            "1": {
              "name": "ACS ACL",
              "policies": "xACSACLx-IP-PERMIT_ALL_IPV4_TRAFFIC-57f6b0d3",
              "security_policy": "Should Secure"
            }
          },
          "session_timeout": {
            "type": "N/A"
          },
          "status": "Authorized",
          "user_name": "08-00-27-3F-F4-27"
        },
        "1062.e519.072e": {
          "acct_session_id": "0x000037fe",
          "common_session_id": "86010F8900002F28A5016B11",
          "current_policy": "C3PL_ISE_210",
          "domain": "DATA",
          "handle": "0x21000fc0",
          "iif_id": "0x273804C8",
          "ipv4_address": "10.15.1.176",
          "ipv6_address": "Unknown",
          "local_policies": {
            "template": {
              "DEFAULT_LINKSEC_POLICY_SHOULD_SECURE": {
                "priority": 150
              }
            }
          },
          "method_status": {
            "dot1x": {
              "method": "dot1x",
              "state": "Authc Success"
            },
            "mab": {
              "method": "mab",
              "state": "Stopped"
            }
          },
          "oper_control_dir": "in",
          "oper_host_mode": "multi-auth",
          "server_policies": {
            "3": {
              "name": "ACS ACL",
              "policies": "xACSACLx-IP-PERMIT_ALL_IPV4_TRAFFIC-57f6b0d3"
            },
            "4": {
              "name": "Session-Timeout",
              "policies": "64800 sec"
            }
          },
          "session_timeout": {
            "remaining": "33345s",
            "timeout": "64800s",
            "type": "server"
          },
          "status": "Authorized",
          "timeout_action": "Reauthenticate",
          "user_name": "J2XD0170154"
        }
      }
    }
  }
}
```

**Comment by domachad** [comment] 2021-05-28 15:22
Hi @ahlara-devcore, thank you for the additional information.
Your solution seems to work for this output, but we will have to assess the impact of this change in the schema.

**Comment by domachad** [comment] 2021-05-31 17:47
Hi @ahlara-devcore, your suggestion was accepted and will be incorporated in the next release (version 21.6).
I am closing the issue, but please let us know if you encounter any other problems in the future.

**Closed by domachad** 2021-05-31 17:47 UTC
