### ISSUE TITLE
show bgp all neighbors <neighbor> advertised-routes returns inaccurate number of prefixes

### ISSUE THREAD

**Issue by mupchu** [CiscoTestAutomation/genieparser#486] opened 2021-07-16 00:27 UTC
The parser is returning advertised routes, but I am missing some of the routes.

 *>i 192.168.255.18/31
                       xx.xx.xx.xx1             768    300      0 xxxxx ?

Total number of prefixes 483 
cr2-xxx-xxx-xxx#

In my script I am running:

response2 = Dq(response).contains('neighbor').get_values('advertised')

I am 50 or so routes short.  The missing routes are a little large ('10.105.144.128/25') for instance.  It does not appear to be in the dictionary.  Smaller routing tables appear to be working fine.

**Comment by akhosrav** [comment] 2021-07-19 14:34
Hello @mupchu 
could you please tell me which device/OS the problem occure?

**Comment by mupchu** [comment] 2021-07-19 15:03
This was on an ASR 1002, running 15.6(3)S6

**Comment by akhosrav** [comment] 2021-07-20 13:19
thanks for the reply, would you please update the pyats to the latest version if it's not (the current version is 21.6)

**Comment by akhosrav** [comment] 2021-07-20 14:35
@mupchu 
There is no limit for the routers in the parser,
please provide a full log to insvistigate.

**Comment by mupchu** [comment] 2021-07-20 15:07
I am running the latest version of pyats.  I am missing routes in the results, there are 483 routes being advertised by the last router, and there are only 436 present in the dictionary.  I did notice that some of the routes missing had a longer character count, but that might just be a red herring.  I am also wondering if this might be caused by the fact I do not have write cred's to the devices, so my connection command looks like this: "dev.connect(init_exec_commands=[],init_config_commands=[])"
[pyats_test.zip](https://github.com/CiscoTestAutomation/genieparser/files/6849327/pyats_test.zip)

**Comment by akhosrav** [comment] 2021-07-20 17:05
@mupchu 
Can you please provide 'show command output' and the 'parsed output'

**Comment by mupchu** [comment] 2021-07-20 17:27
sure thing
[output_pyats.zip](https://github.com/CiscoTestAutomation/genieparser/files/6850169/output_pyats.zip)

**Comment by akhosrav** [comment] 2021-07-20 17:30
@mupchu 
Thanks we will check it

**Comment by akhosrav** [comment] 2021-07-27 21:13
@mupchu 
It seems the error comes from the output which values are not in the same line
![75365693-c165-4ad3-bc4b-7f75b3ab372b](https://user-images.githubusercontent.com/85900072/127228172-024077be-7468-4692-a173-fc972d556307.PNG)

**Comment by akhosrav** [comment] 2021-07-27 21:13
will you please check and match if the count of them are matched with short routes

**Comment by mupchu** [comment] 2021-07-28 00:29
I think i have what you need.  look at the attached documents.  The txt file called missing routes contains all the routes that were missing from the pyats output.  I think when you look at the output file (in a word doc) it will explain what is going on.  All the prefixes that push the character limit to a new line, are being tossed out and not not captured in the parser.
[missing routes2.zip](https://github.com/CiscoTestAutomation/genieparser/files/6889442/missing.routes2.zip)

**Comment by akhosrav** [comment] 2021-07-28 13:16
@mupchu 
Thanks a lot for reply,
I will look to it

**Comment by akhosrav** [comment] 2021-07-28 17:58
@mupchu 
The new pyats have been released please update and check if the problem is solved.

**Comment by mupchu** [comment] 2021-07-28 22:27
I upgraded to the new version, but had the same results. Let me know if you want me to pull all the logs and doc's.

**Comment by domachad** [comment] 2021-08-04 13:37
Hi @mupchu, have you changed the size of your terminal? 
If not, can you try changing it to something greater than the default (80 chars)?

**Comment by mupchu** [comment] 2021-08-04 14:47
by default pyats changes the term len to 0 so that there is no pause in the output.  I have tried adjusting both the length and width of the terminal but there is still a wrap around:

![image](https://user-images.githubusercontent.com/43792509/128202109-c8a307c2-d92f-429f-9237-7f5cff987f09.png)

**Comment by domachad** [comment] 2021-08-04 17:46
Hi @mupchu, thank you for the quick reply.

The parser will have to be modified to support this case. 
Once ready, it will be available to you in the next release (version 21.8)

**Comment by domachad** [comment] 2021-08-25 16:06
Hi @mupchu 
A fix has been approved and merged to genieparser.
It will be available to you once version 21.8 is released.
I will close the issue, but please feel free to leave any comments or reopen the issue if the problem persists.

Thank you

**Closed by domachad** 2021-08-25 16:06 UTC
Labels: bug, question
